title: OCTO Provence
email: provence@octo.com
description: |
    OCTO Provence website
baseurl: ''
url: 'https://provence.octo.com'
twitter: 'https://twitter.com/octoprovence'
google_analytics:

markdown: kramdown
theme: minima
plugins:
    - jekyll-feed
exclude:
    - Gemfile
    - Gemfile.lock
