title: OCTO Provence
email: provence@octo.com
description: |
    Consommez local et durable :
    OCTO Provence, le cabinet de conseil tech, méthodo et UX en circuit-court sur la région Aix - Marseille !
baseurl: ''
url: 'https://provence.octo.com'
google_analytics: UA-142862370-1
twitter:
    username: octoprovence
    card: summary
social:
    name: OCTO chti
    links:
        - https://twitter.com/OctoProvence
        - https://github.com/octo-technology-provence
markdown: kramdown
theme: minima
plugins:
    - jekyll-feed
exclude:
    - Gemfile
    - Gemfile.lock
categories: [newsletter]
